ARG ROCM_VER=5.7.3
# options:
# - rocm5.4.6-mpich3.4.3-ubuntu22
# - rocm5.6.0-mpich3.4.3-ubuntu22
# - rocm5.6.1-mpich3.4.3-ubuntu22
# - rocm5.7.3-mpich3.4.3-ubuntu22
# - rocm6.0.2-mpich3.4.3-ubuntu22
# - rocm6.1-mpich3.4.3-ubuntu22

##YOU WILL WANT TO CHANGE THIS FOR YOUR PARTICULAR MACHINE
#Base image ROCm
FROM quay.io/pawsey/rocm-mpich-base:rocm${ROCM_VER}-mpich3.4.3-ubuntu22

ENV WODEN_TAG=compile_both_CUDA_and_HIP

##YOU WILL WANT TO CHANGE THIS FOR YOUR PARTICULAR MACHINE
##Maybe someone intelligent could make this a multi-arch build
ENV HIP_ARCH=gfx90a

##install the dependencies
ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update -y && \
    apt-get -y install \
            software-properties-common \
            tzdata \
            build-essential \
            pkg-config \
            cmake \
            curl \
            git \
            autoconf \
            libtool \
            unzip \
            wget \
            zip \
            python3-pip \
            libhdf5-serial-dev \
            && apt-get clean all \
            && rm -rf /var/lib/apt/lists/*

# Get Rust
RUN mkdir -m755 /opt/rust /opt/cargo
ENV RUSTUP_HOME=/opt/rust CARGO_HOME=/opt/cargo PATH=/opt/cargo/bin:$PATH
ENV RUST_VERSION=1.79
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain=$RUST_VERSION

# hyperbeam used for MWA primary beam
RUN wget https://github.com/MWATelescope/mwa_hyperbeam/archive/refs/tags/v0.9.2.tar.gz \
  && tar -xvf v0.9.2.tar.gz \
  && cd mwa_hyperbeam-0.9.2 \
  && export HYPERBEAM_HIP_ARCH=$HIP_ARCH \
  && /opt/cargo/bin/cargo build --release --features=hip,hdf5-static \
  && cd /

## clone the release verion of WODEN and complile the C/CUDA code
RUN git clone -b $WODEN_TAG https://github.com/JLBLine/WODEN.git \
  && cd WODEN \
  && mkdir build && cd build \
  && cmake .. -DUSE_HIP=ON -DHIP_ARCH=gfx90a \
           -DHBEAM_INC=/mwa_hyperbeam-0.9.2/include/ \
           -DHBEAM_LIB=/mwa_hyperbeam-0.9.2/target/release/libmwa_hyperbeam.so \
  && make
  
##Now do the pip install
RUN cd /WODEN && pip install -r requirements.txt && pip install .

# unity - used for testing
RUN cd / && git clone https://github.com/ThrowTheSwitch/Unity.git

##install the tests. no sense in running the tests of course because
##that is user GPU dependent. But we can install them.
RUN cd /WODEN/build && cmake .. -DTARGET_GROUP=test -DUNITY_ROOT=/Unity \
    && make -j4

##copy the MWA primary beam files
RUN cd / && mkdir MWA_beam_files && cd MWA_beam_files \
    && wget http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 \
    && wget http://ws.mwatelescope.org/static/MWA_embedded_element_pattern_rev2_interp_167_197MHz.h5

##make some environment variables
ENV MWA_FEE_HDF5=/MWA_beam_files/mwa_full_embedded_element_pattern.h5
ENV MWA_FEE_HDF5_INTERP=/MWA_beam_files/MWA_embedded_element_pattern_rev2_interp_167_197MHz.h5