ARG ROCM_VER=5.7.3
# options:
# - rocm5.4.6-mpich3.4.3-ubuntu22
# - rocm5.6.0-mpich3.4.3-ubuntu22
# - rocm5.6.1-mpich3.4.3-ubuntu22
# - rocm5.7.3-mpich3.4.3-ubuntu22
# - rocm6.0.2-mpich3.4.3-ubuntu22
# - rocm6.1-mpich3.4.3-ubuntu22

##YOU WILL WANT TO CHANGE THIS FOR YOUR PARTICULAR MACHINE
#Base image ROCm
FROM quay.io/pawsey/rocm-mpich-base:rocm${ROCM_VER}-mpich3.4.3-ubuntu22

ENV WODEN_TAG=v2.5.0-alpha
ENV EVERYBEAM_TAG=mwa_python_wrapper
ENV HYPER_VERSION=0.10.0
ENV RUST_VERSION=1.84.0

##YOU WILL WANT TO CHANGE THIS FOR YOUR PARTICULAR MACHINE
##Maybe someone intelligent could make this a multi-arch build
ENV HIP_ARCH=gfx90a

RUN echo "Building for HIP_ARCH=$HIP_ARCH"
RUN echo "Using WODEN tag ${WODEN_TAG}"
RUN echo "Using EveryBeam tag ${EVERYBEAM_TAG}"
RUN echo "Using Hyperbeam version ${HYPER_VERSION}"

##install the dependencies
ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update -y && \
    apt-get -y install \
            software-properties-common \
            tzdata \
            build-essential \
            pkg-config \
            cmake \
            curl \
            git \
            autoconf \
            libtool \
            unzip \
            wget \
            zip \
            python3-pip \
            libhdf5-serial-dev \
            wget git make cmake g++ doxygen \
            libboost-all-dev libhdf5-dev libfftw3-dev \
            libblas-dev liblapack-dev libxml2-dev \
            libgtkmm-3.0-dev libpython3-dev python3-distutils \
            casacore-dev libcfitsio-dev wcslib-dev \
            && apt-get clean all \
            && rm -rf /var/lib/apt/lists/*

##Update the data dir in casacore
RUN wget -q ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar \
    && tar -xf WSRT_Measures.ztar -C /var/lib/casacore/data/

RUN mkdir -p /everybeam_install
RUN git clone -b $EVERYBEAM_TAG --recursive -j4 https://git.astron.nl/RD/EveryBeam.git \
  && cd EveryBeam \
  && mkdir -p build && cd build \
  && cmake .. -DCMAKE_INSTALL_PREFIX=/everybeam_install \
  && make \
  && make install
    


# Get Rust
RUN mkdir -m755 /opt/rust /opt/cargo
ENV RUSTUP_HOME=/opt/rust CARGO_HOME=/opt/cargo PATH=/opt/cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain=$RUST_VERSION

# hyperbeam used for MWA primary beam
RUN wget https://github.com/MWATelescope/mwa_hyperbeam/archive/refs/tags/v${HYPER_VERSION}.tar.gz \
  && tar -xvf v${HYPER_VERSION}.tar.gz \
  && cd mwa_hyperbeam-${HYPER_VERSION} \
  && export HYPERBEAM_HIP_ARCH=$HIP_ARCH \
  && /opt/cargo/bin/cargo build --release --features=hip,hdf5-static \
  && cd /

## clone the release verion of WODEN and complile the C/CUDA code
RUN git clone -b $WODEN_TAG https://github.com/JLBLine/WODEN.git \
  && cd WODEN \
  && mkdir build && cd build \
  && cmake .. -DUSE_HIP=ON -DHIP_ARCH=gfx90a \
    -DHBEAM_INC=/mwa_hyperbeam-${HYPER_VERSION}/include/ \
    -DHBEAM_LIB=/mwa_hyperbeam-${HYPER_VERSION}/target/release/libmwa_hyperbeam.so \
    -DEBEAM_INSTALL=/everybeam_install/ \
    -DEBEAM_ROOT=/EveryBeam/ \
  && make
  
##Now do the pip install
RUN cd /WODEN && pip install -r requirements.txt && pip install .
RUN pip install --upgrade astropy-iers-data

RUN mkdir -p /astropy_data
ENV ASTROPY_DATA=/astropy_data

RUN wget https://datacenter.iers.org/data/9/finals2000A.all
RUN mv finals2000A.all /astropy_data/finals2000A.all

RUN python3 /WODEN/docker/fetch_iers_data.py

# # unity - used for testing
# RUN cd / && git clone https://github.com/ThrowTheSwitch/Unity.git

# ##install the tests. no sense in running the tests of course because
# ##that is user GPU dependent. But we can install them.
# RUN cd /WODEN/build && cmake .. -DTARGET_GROUP=test -DUNITY_ROOT=/Unity \
#     && make -j4

# ##copy the MWA primary beam files
# RUN cd / && mkdir MWA_beam_files && cd MWA_beam_files \
#     && wget http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 \
#     && wget http://ws.mwatelescope.org/static/MWA_embedded_element_pattern_rev2_interp_167_197MHz.h5

# ##make some environment variables
# ENV MWA_FEE_HDF5=/MWA_beam_files/mwa_full_embedded_element_pattern.h5
# ENV MWA_FEE_HDF5_INTERP=/MWA_beam_files/MWA_embedded_element_pattern_rev2_interp_167_197MHz.h5